import InvocationRepeat from '../../../domains/common/InvocationRepeat';
import { TKeys } from '../../../locales/constants';

export type ImmunizationPeriod = 'morning' | 'evening';

export const immunizationData: Record<ImmunizationPeriod, InvocationRepeat[]> = {
  morning: [
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_1, repeat: 10 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_2, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_3, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_4, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_5, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_6, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_7, repeat: 7 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_8, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_9, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_10, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_11, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_12, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_13, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_14, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_15, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_16, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_17, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_18, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_19, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_20, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_21, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_22, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_23, repeat: 4 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_24, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_25, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_26, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_27, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_28, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_29, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_30, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_31, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_32, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_33, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_34, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_35, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_36, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_37, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_38, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_39, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_MORNING_40, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_CONCLUSION, repeat: 1 },
  ],
  evening: [
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_1, repeat: 10 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_2, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_3, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_4, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_5, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_6, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_7, repeat: 7 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_8, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_9, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_10, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_11, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_12, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_13, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_14, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_15, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_16, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_17, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_18, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_19, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_20, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_21, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_22, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_23, repeat: 4 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_24, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_25, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_26, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_27, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_28, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_29, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_30, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_31, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_32, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_33, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_34, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_35, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_36, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_37, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_38, repeat: 3 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_COMMON_39, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_EVENING_40, repeat: 1 },
    { key: TKeys.INVOCATIONS_IMMUNIZATION_CONCLUSION, repeat: 1 },
  ],
};
